GET http://localhost:3000/users

###


POST http://localhost:3000/login
Content-Type: application/json

# {
#     "username": "mbuendia@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

# {
#     "username": "jmagnaye@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

# {
#     "username": "ragulto@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

{
    "username": "jaguilar@optimizex.com",
    "password": "whoLetDaDogszx0ut"
}

###



POST http://localhost:3000/post
Content-Type: application/json

# {
#     "username": "mbuendia@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

# {
#     "username": "jmagnaye@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

# {
#     "username": "ragulto@optimizex.com",
#     "password": "whoLetDaDogszx0ut"
# }

{
    "userId": "jaguilar@optimizex.com",
}